### ISSUE TITLE
BUG - [your bug title here]

### ISSUE THREAD

**Issue by ayushonplan** [fivetran/dbt_xero#20]
**Are you a current Fivetran customer?** 
yes

**Describe the bug**
In the report generated by Xero we have some field values positive for PL but in the report generated by fivetran dbt package 
of column net_amount we have those value as negative for some accounts although we have positive values in the source table but the transformation written in the dbt doesn't fetch those values .

**Steps to reproduce**
1.Go to the Fivetran dashboard and create a connector using Xero as the source and BigQuery as the destination.
2. add transformation for connector using Fivetran Xero DBT package.
3. after running sync you will get reports generated through the DBT package in BigQuery.
4.Now Just compare reports value with original Xero reports.

**Expected behavior**
we should get the values for net_income positive in the final report 
**Project variables configuration**

```yml

name: 'client_name'
profile: 'my-bigquery-db'
version: '0.3.0'
config-version: 2
require-dbt-version: [">=0.20.0"]

vars:
  xero_schema: xero_five_tran
  xero_database: 
  xero_five_tran:
    account: "{{ ref('stg_xero__account') }}" 
    contact: "{{ ref('stg_xero__contact') }}" 
    invoice_line_item: "{{ ref('stg_xero__invoice_line_item') }}" 
    invoice: "{{ ref('stg_xero__invoice') }}" 
    journal_line: "{{ ref('stg_xero__journal_line') }}" 
    journal: "{{ ref('stg_xero__journal') }}" 
    organization: "{{ ref('stg_xero__organization') }}" 
    credit_note: "{{ ref('stg_xero__credit_note') }}" 
    bank_transaction: "{{ ref('stg_xero__bank_transaction') }}" 
  
models:
 :
    +materialized: table
    +schema: xero
    

```

**Package Version**
package: fivetran/xero_source
version: [">=0.2.0","<0.3.0"]

```yml
packages:
  - package: fivetran/xero_source
    version: [">=0.3.0","<0.4.0"]
```

**Warehouse**

 
- [x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**

**Please indicate the level of urgency** 
This is really important because, the client needs the report, but as I told the report we are generating through the Fivetran DBT package has the wrong net_amount which is blocking us. This will really affect our relationship with the customer. If we don't deliver it on time it may result in fine also.

**Are you interested in contributing to this package?** 
no
- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [x] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
